{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"Timed out retrying after 4000ms: Expected to find element: `//a[text()=' Customers']`, but never found it.  Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Handle Tables`","children":[{"name":"Handle Tables \"before each\" hook: Login for \"Read all the rows & Columns data in the first page\"","uid":"8c03b079a18f2fce","parentUid":"775bb0d9fe29ee7020c309909cbaed55","status":"failed","time":{"start":1718608250000,"stop":1718608250000,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"775bb0d9fe29ee7020c309909cbaed55"},{"name":"The following error originated from your application code, not from Cypress.    > Cannot read properties of undefined (reading 'plugins')  When Cypress detects uncaught errors originating from your application it will automatically fail the current test.  This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.  https://on.cypress.io/uncaught-exception-from-application  Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Handle Tables`","children":[{"name":"Handle Tables \"before each\" hook: Login for \"Check Number Rows & Columns\"","uid":"15f4783ea2337309","parentUid":"0a1247ad84d6a8a377d8a16b8869ebe0","status":"failed","time":{"start":1718608446000,"stop":1718608446000,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"0a1247ad84d6a8a377d8a16b8869ebe0"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}